# profiles.yml

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: heroic-passkey-401714
      dataset: new_dataset
      threads: 1
      keyfile: dbt-user-creds.json